# This file is an example of how to change the settings.

# This file is so you can customize: 
# - tab name & tab count
# - widgets in each tab
# - save location for each tab

# The goal of this ini file is to give control and to setup a quick and efficient way to organize mass amounts of file scans.













[Tabs]
Count=3

[Tab0]
Name=Job Tickets

ButtonCount=1

Button0.X=550
Button0.Y=60
Button0.Width=80
Button0.Height=22
Button0.Text=Save

FieldCount=3
Field0.Label=Customer Name
Field0.Control=EDIT
Field0.Source=
Field0.X=50
Field0.Y=80
Field0.Width=180
Field0.Height=22

Field1.Label=PO Number
Field1.Control=EDIT
Field1.Source=
Field1.X=50
Field1.Y=140
Field1.Width=180
Field1.Height=22

Field2.Label=Current Year
Field2.Control=COMBO
Field2.Source=Years
Field2.X=300
Field2.Y=80
Field2.Width=200
Field2.Height=230

Path1=C:\Users\12096\DropBox\Harrison's DropBox\{Field:Current Year}\Job Tickets {Field:Current Year}\
SavedFileName={Field:Customer Name} #{Field:PO Number}.pdf
Field2.LastValue=2025

[Tab1]
Name=Invoices

ButtonCount=2

Button0.X=550
Button0.Y=60
Button0.Width=80
Button0.Height=22
Button0.Text=Save

Button1.Text=Add To List
Button1.Function=OpenList
Button1.X=300
Button1.Y=140
Button1.Width=120
Button1.Height=22

FieldCount=2
Field0.Label=Invoice Date
Field0.Control=EDIT
Field0.Source=
Field0.X=50
Field0.Y=80
Field0.Width=180
Field0.Height=22

Field1.Label=Current Year
Field1.Control=COMBO
Field1.Source=Years
Field1.X=300
Field1.Y=80
Field1.Width=200
Field1.Height=230

Field2.Label=Current Month
Field2.Control=COMBO
Field2.Source=Months	
Field2.X=300
Field2.Y=140
Field2.Width=200
Field2.Height=230

Path1=C:\Users\12096\DropBox\Harrison's DropBox\{Field:Current Year}\Invoices {Field:Current Year}\
SavedFileName={Field:Invoice Date}.pdf
Field1.LastValue=2026



[Tab2]
Name=Parts Receipts

ButtonCount=1

Button0.X=550
Button0.Y=60
Button0.Width=80
Button0.Height=22
Button0.Text=Save

FieldCount=3
Field0.Label=Company
Field0.Control=COMBO
Field0.Source=Companies
Field0.X=50
Field0.Y=80
Field0.Width=200
Field0.Height=230
Field0.SkipRecent=1

Field1.Label=Current Year
Field1.Control=COMBO
Field1.Source=Years
Field1.X=300
Field1.Y=80
Field1.Width=200
Field1.Height=230
Field1.SkipRecent=0

Field2.Label=Current Month
Field2.Control=COMBO
Field2.Source=Months	
Field2.X=300
Field2.Y=140
Field2.Width=200
Field2.Height=230

Path1=C:\PlaceFileHere\
SavedFileName={Field:Company}.pdf




Field0.LastValue=Wrecking Yard
Field1.LastValue=2025
Field2.LastValue=January



[Undo]







[Companies]
1=Autozone
2=Fast Undercar
3=Honda
4=Napa
5=O'Reilly's
6=Place
7=Worldpac
8=Wrecking Yard


[Months]
1=April
2=August
3=December
4=February
5=January
6=July
7=June
8=March
9=May
10=November
11=October
12=September


[Years]
1=2020
2=2021
3=2022
4=2023
5=2024
6=2025
7=2026
8=2027
9=2028
10=2029
11=2030
